# -*- coding: utf-8 -*-
"""solving probem using python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eO4811MpFwvX-DfeQAY8zL3VYlg4v2ak
"""

timing = float(input('enter the time spend on the trip '))
speed = float(input('enter the averege speed '))

print(timing, speed)

distance = timing * speed 
liters_used = distance / 12

print('averege speed: ', speed)
print('timing spend on the trip: ', timing)
print('distance covered: ', distance)
print('quantity in liters: ', round(liters_used,1))