# -*- coding: utf-8 -*-
"""using if in python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrE_9nuyPs0oDwFREvdhf2BZINnE32ON
"""

M1 = float(input('write your note: '))
M2 = float(input('write your note: '))
M3 = float(input('write your note: '))

print(M1, M2, M3)

finalnote = (M1 + M2 + M3) / 3 
print(finalnote)

if finalnote >= 0.0 and finalnote <= 4.0:
  print('failed')
elif finalnote >= 4.1 and finalnote <= 6.0:
  test = float(input('write your test note'))
  if test >= 6.0:
    print('test aproved')
  else:
    print('test reproved')
else: 
    print('student aproved')